-- Müller App · Supabase (plan gratuito)
-- Ejecuta esto en: SQL Editor → New query → Run
-- Auth: Authentication → Providers → Email → puedes desactivar "Confirm email" para pruebas locales.

-- Perfiles públicos (lectura para todos los usuarios autenticados / anon según políticas)
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using ((select auth.uid()) = id);

-- Perfil al registrarse (metadata display_name desde la app)
create or replace function public.muller_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, updated_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', 'Estudiante'),
    now()
  )
  on conflict (id) do update
    set display_name = excluded.display_name,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.muller_handle_new_user();

-- Liga semanal: una fila por usuario y semana (week_key = lunes ISO YYYY-MM-DD)
create table if not exists public.league_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  week_key text not null,
  score int not null default 0,
  display_name text,
  updated_at timestamptz default now(),
  unique (user_id, week_key)
);

create index if not exists league_scores_week_score_idx
  on public.league_scores (week_key, score desc);

alter table public.league_scores enable row level security;

drop policy if exists "league_select_all" on public.league_scores;
create policy "league_select_all"
  on public.league_scores for select
  using (true);

drop policy if exists "league_insert_own" on public.league_scores;
create policy "league_insert_own"
  on public.league_scores for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "league_update_own" on public.league_scores;
create policy "league_update_own"
  on public.league_scores for update
  using ((select auth.uid()) = user_id);
